import '../styles/globals.scss';

import Head from 'next/head';
import type { AppProps } from 'next/app';
import { PersistGate } from 'redux-persist/integration/react';
import { Provider } from 'react-redux';
import { DndProvider } from 'react-dnd';
import { HTML5Backend } from 'react-dnd-html5-backend';

import { wrapper, store, persistor } from '../store';
import { Header } from '../components/header';
import { Footer } from '../components/footer';

function App({ Component, pageProps }: AppProps) {
  return (
    <Provider store={store}>
      <DndProvider backend={HTML5Backend}>
        <PersistGate loading={<div>Loading...</div>} persistor={persistor}>
          <div className="grid grid-rows-[auto_1fr_auto] min-h-screen">
            <Head>
              <title>Donut</title>
              <meta name="description" content="Generated by create next app" />
              <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header></Header>
            <Component {...pageProps} />
            <div id="modal-root"></div>
            <Footer></Footer>
          </div>
        </PersistGate>
      </DndProvider>
    </Provider>
  );
}

export default wrapper.withRedux(App);
