import '../styles/globals.css';

import Head from 'next/head';
import type { AppProps } from 'next/app';
import { Provider } from 'react-redux';

import { store } from '../store';
import { wrapper } from '../store';
import { Header } from '../components/header';
import { Footer } from '../components/footer';

function App({ Component, pageProps }: AppProps) {
  return (
    <div className="grid grid-rows-[70px_1fr_auto] h-full">
      <Head>
        <title>Bun app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header></Header>
      <Component {...pageProps} />
      <Footer></Footer>
    </div>
  );
}

export default wrapper.withRedux(App);
