import { Header } from '../components/header';
import { Footer } from '../components/footer';
import { Section } from '../components/section';
import Head from 'next/head';
import { ICategory } from '../interfaces/category';
interface HomeProps {
  categories: [ICategory];
}
const Home = ({ categories }: HomeProps) => {
  const incomes: ICategory[] = [];
  const assets: ICategory[] = [];
  const expenses: ICategory[] = [];
  categories.forEach((item: ICategory) => {
    switch (item.type) {
      case 'income':
        incomes.push(item);
        break;
      case 'asset':
        assets.push(item);
        break;
      case 'expense':
        expenses.push(item);
        break;
    }
  });

  return (
    <>
      <Head>
        <title>Bun app</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="grid grid-rows-[70px_1fr_auto] h-full">
        <Header />
        <main className="grid grid-rows-[120px_120px_minmax(120px,_1fr)] my-2">
          <div className="container mx-auto px-2">
            <Section data={incomes}></Section>
            <Section data={assets}></Section>
            <Section data={expenses}></Section>
          </div>
        </main>
        <Footer></Footer>
      </div>
    </>
  );
};

export async function getServerSideProps() {
  const response = await fetch(`https://bun-app.herokuapp.com/api/category`);
  const categories = await response.json();
  return {
    props: { categories },
  };
}
export default Home;
